### ISSUE TITLE
filtering in a stream doesn't work as expected

### ISSUE THREAD

**Issue by dickshaydle** [sharkdp/shell-functools#41] opened 2020-11-30 00:51 UTC
if i look in the stream of syslog for a word, the output is as expected
``` bash
>tail -f /var/log/syslog | map contains Attached  
False
False
False
False
True
False
```
but if i filter for True nothing comes out
``` bash
>tail -f /var/log/syslog | map contains Attached | filter equals True 
```

Strangely it works if the stream is saved to a file before
``` bash
>tail -f /var/log/syslog > syslog.temp
>cat syslog.temp | map contains Attached | filter equals True
True
True

```

latest version: 0.3.0

**Comment by dickshaydle** [comment] 2020-11-30 01:35
maybe it has something to do with the buffer.
A similar similar command with `grep` shows the same problem
``` bash
>tail -f /var/log/syslog | grep --line-buffered Attached | while read line ; do echo "$line"; done
```
but with the `--line-buffered` parameter it runs smoothly

``` bash
>tail -f /var/log/syslog | grep --line-buffered Attached | while read line ; do echo "$line"; done
Nov 30 02:30:23 mycomputername kernel: [498264.335276] sd 8:0:0:0: [sdc] Attached SCSI removable disk
...
```

**Comment by dickshaydle** [comment] 2020-11-30 02:14
`unbuffer -p` has an effect:
``` bash
tail -f /var/log/syslog | unbuffer -p map contains Attached | unbuffer -p map append " " | map replace True "aaaa"
```
is responding but 
``` bash
tail -f /var/log/syslog | unbuffer -p map contains Attached | unbuffer -p map append " " | filter eq True
```
is not.

**Comment by sharkdp** [comment] 2020-12-02 07:03
Thank you for reporting this. That seems to be a problem in `filter`, indeed.

Another way to reproduce this:
```
(echo "A"; sleep 1; echo "B"; sleep 1; echo "A") | map contains A | filter equals True
```
This outputs
```
True
True
```
as it should, but the output is not streaming. Both lines are only printed after 2 seconds

**Comment by sharkdp** [comment] 2020-12-02 07:07
Small correction: the problem seems to be with buffered *writing* in the `map` command, not with reading in `filter`. Observe:
```
(echo "A"; sleep 1; echo "B"; sleep 1; echo "A") | map append C

# versus

(echo "A"; sleep 1; echo "B"; sleep 1; echo "A") | map append C | cat
```

The first one streams to the console, the second does not.

**Comment by sharkdp** [comment] 2020-12-02 07:09
Should hopefully be fixed via  c79d764

**Closed** 2020-12-02 07:09 UTC
Labels: bug, help wanted

**Comment by dickshaydle** [comment] 2020-12-06 07:36
great it runs now.

Maybe this is not the right place, but i want want to say that your coding work really is bewundernswert. I absolutely love all your projects i've seen. Great sense for style and simplicity.

**Comment by sharkdp** [comment] 2020-12-06 18:29
> Maybe this is not the right place, but i want want to say that your coding work really is bewundernswert. I absolutely love all your projects i've seen. Great sense for style and simplicity.

Thank you very much for the feedback!
